name: Publish Services

on:
  push: {}

permissions:
  contents: write
  packages: write

jobs:
  artifact-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Install Dagger CLI
        env:
          DAGGER_VERSION: v0.6.2
        run: |
          cd /usr/local
          curl -L https://dl.dagger.io/dagger/install.sh | VERSION=$DAGGER_VERSION sh
          cd -

      - name: Publish artifact-service
        run: dagger do -c services/artifact/ci/dagger.json publish main

